name: yaml_writer
description: A library to write YAML documents, supporting Object encoding and 'dart:convert' 'Converter'.
version: 1.1.0
homepage: https://github.com/gmpassos/yaml_writer

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  dependency_validator: ^3.2.2
  coverage: ^1.6.1
