name: yaml_writer
description: A library to write YAML documents, supporting Object encoding and 'dart:convert' 'Converter'.
version: 1.0.2
homepage: https://github.com/gmpassos/yaml_writer

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.12
  dependency_validator: ^3.2.0
  coverage: ^1.1.0
